### ISSUE TITLE
Prune by volume produces - AttributeError - Can't pickle local object

### ISSUE THREAD

**Issue by SridharJagannathan** [schlegelp/navis#8]
This is also a new error in functionality that was working earlier:
```
#al - any mesh like antenna lobe mesh
#intraglom_skel - this could be any skeleton
intraglom_skel.prune_by_volume(al,mode = 'IN', prevent_fragments = True)
```
This results in
```
 Reason: 'AttributeError("Can't pickle local object 'subgraph_view.<locals>.reverse_edge'")'
```

**Comment by SridharJagannathan** [comment]
Better example here:
```
n = navis.example_neurons(10)
lh = navis.example_volume('LH')

n_lh = n.prune_by_volume(lh, mode = 'IN',prevent_fragments = True, inplace=False)

```
Produces the error
```
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/pool.py", line 127, in worker
    put((job, i, result))
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/queues.py", line 358, in put
    obj = _ForkingPickler.dumps(obj)
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'subgraph_view.<locals>.reverse_edge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/pool.py", line 129, in worker
    wrapped = MaybeEncodingError(e, result[1])
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/pool.py", line 82, in __init__
    self.value = repr(value)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 126, in __repr__
    return str(self.summary())
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 353, in summary
    s = pd.Series([getattr(self, at, 'NA') for at in props],
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 353, in <listcomp>
    s = pd.Series([getattr(self, at, 'NA') for at in props],
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 698, in __getattr__
    return super().__getattr__(key)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 118, in __getattr__
    return len(getattr(self, key[2:]))
TypeError: object of type 'NoneType' has no len()

```

**Comment by SridharJagannathan** [comment]
Furthermore, the problem seems to be with the parameter, `prevent_fragments = True`, if I don't have this parameter set, the functionality works fine.

**Comment by schlegelp** [comment]
That's actually a fairly complicated bug. What's happening here is this:

When you call `n.prune_by_volume` it wraps the original function and (by default) distributes the pruning of individual neurons across multiple cores (sort of like `nlapply` in R). This requires objects (including the neurons) to be first serialised (pickled) before being transferred to the respective processes and then, conversely, be unpickled when the results come back.

If `prevent_fragments=True` a networkx subgraph view (read-only) is attached to the neurons during the subsetting which is then causing problems during unpickling. Seems to be related to [this](https://github.com/networkx/networkx/issues/3128) issue.

This parallel feature is still "in flux" and I was meaning to make it more explicit.

Possible solutions:
Write custom pickle/unpickle methods for neurons that make a copy of the graph if `nx.is_frozen(g)=True)`.

Workarounds until then:
Do not use multiprocessing (faster for small numbers of neurons anyway).
```Python
# Either deactivate parallel processing 
n.use_threading = False
n_lh = n.prune_by_volume(lh, mode='IN', prevent_fragments=True, inplace=False)

# Use the original function
n_lh = navis.in_volume(n, lh, mode='IN', prevent_fragments=True, inplace=False)
```

By-the-by:
In the process of debugging this I ran into another issue specific to your example: the raycasting library [ncollpyde](https://github.com/clbarnes/ncollpyde) returns empty neurons in this particular situation because of negative coordinates (I opened an issue [here](https://github.com/clbarnes/ncollpyde/issues/8)).

**Comment by schlegelp** [comment]
6a6631954f5f04a297b092436f02b60050db5fe4 should have fixed the issue. Try again please.

**Comment by SridharJagannathan** [comment]
Thanks @schlegelp but it seems it is creating an error now..

```


---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neuronlist.py", line 721, in _worker_wrapper
    return f(*args, **kwargs)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 1422, in prune_by_volume
    x = self.copy()
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 1013, in copy
    x = Neuron(self.nodes)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 703, in __getattr__
    return super().__getattr__(key)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 125, in __getattr__
    raise AttributeError(f'Attribute "{key}" not found')
AttributeError: Attribute "nodes" not found
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-113-211a25e8c9dd> in <module>
----> 1 intraglom_skel_pruned = intraglom_skel.prune_by_volume(v_mesh,mode = 'IN',prevent_fragments = False, inplace=False)

~/anaconda3/lib/python3.7/site-packages/navis/core/neuronlist.py in __call__(self, *args, **kwargs)
    700                                    desc=self.desc,
    701                                    disable=config.pbar_hide,
--> 702                                    leave=config.pbar_leave))
    703             pool.close()
    704             pool.join()

~/anaconda3/lib/python3.7/site-packages/tqdm/notebook.py in __iter__(self, *args, **kwargs)
    216     def __iter__(self, *args, **kwargs):
    217         try:
--> 218             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    219                 # return super(tqdm...) will not catch exception
    220                 yield obj

~/anaconda3/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
   1127 
   1128         try:
-> 1129             for obj in iterable:
   1130                 yield obj
   1131                 # Update and possibly print the progressbar.

~/anaconda3/lib/python3.7/multiprocessing/pool.py in <genexpr>(.0)
    323                     result._set_length
    324                 ))
--> 325             return (item for chunk in result for item in chunk)
    326 
    327     def imap_unordered(self, func, iterable, chunksize=1):

~/anaconda3/lib/python3.7/multiprocessing/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

~/anaconda3/lib/python3.7/multiprocessing/pool.py in worker()
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

~/anaconda3/lib/python3.7/multiprocessing/pool.py in mapstar()
     42 
     43 def mapstar(args):
---> 44     return list(map(*args))
     45 
     46 def starmapstar(args):

~/anaconda3/lib/python3.7/site-packages/navis/core/neuronlist.py in _worker_wrapper()
    719 def _worker_wrapper(x: Sequence):
    720     f, args, kwargs = x
--> 721     return f(*args, **kwargs)
    722 
    723 

~/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py in prune_by_volume()
   1420             x = self
   1421         else:
-> 1422             x = self.copy()
   1423 
   1424         intersection.in_volume(x, v, inplace=True,

~/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py in copy()
   1011         """
   1012         # Generate new neuron
-> 1013         x = Neuron(self.nodes)
   1014         # Override with this neuron's data
   1015         x.__dict__.update({k: copy.copy(v) for k, v in self.__dict__.items()})

~/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py in __getattr__()
    701 
    702         # Last ditch effort - maybe the base class knows the key?
--> 703         return super().__getattr__(key)
    704 
    705     def __truediv__(self, other):

~/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py in __getattr__()
    123             return None
    124 
--> 125         raise AttributeError(f'Attribute "{key}" not found')
    126 
    127     def __str__(self):

AttributeError: Attribute "nodes" not found

```

**Comment by schlegelp** [comment]
This is hard to debug without knowing your code. Could you please re-run your minimal example in a fresh session:
```Python
n = navis.example_neurons(10)
lh = navis.example_volume('LH')

n_lh = n.prune_by_volume(lh, mode = 'IN',prevent_fragments = True, inplace=False)
```

**Comment by SridharJagannathan** [comment]
I get the same error with the mwe as well. 
```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sri/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neuronlist.py", line 721, in _worker_wrapper
    return f(*args, **kwargs)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 1422, in prune_by_volume
    x = self.copy()
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 1013, in copy
    x = Neuron(self.nodes)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 703, in __getattr__
    return super().__getattr__(key)
  File "/Users/sri/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py", line 125, in __getattr__
    raise AttributeError(f'Attribute "{key}" not found')
AttributeError: Attribute "nodes" not found
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-122-886e083a0f3f> in <module>
      2 lh = navis.example_volume('LH')
      3 
----> 4 n_lh = n.prune_by_volume(lh, mode = 'IN',prevent_fragments = True, inplace=False)

~/anaconda3/lib/python3.7/site-packages/navis/core/neuronlist.py in __call__(self, *args, **kwargs)
    700                                    desc=self.desc,
    701                                    disable=config.pbar_hide,
--> 702                                    leave=config.pbar_leave))
    703             pool.close()
    704             pool.join()

~/anaconda3/lib/python3.7/site-packages/tqdm/notebook.py in __iter__(self, *args, **kwargs)
    216     def __iter__(self, *args, **kwargs):
    217         try:
--> 218             for obj in super(tqdm_notebook, self).__iter__(*args, **kwargs):
    219                 # return super(tqdm...) will not catch exception
    220                 yield obj

~/anaconda3/lib/python3.7/site-packages/tqdm/std.py in __iter__(self)
   1127 
   1128         try:
-> 1129             for obj in iterable:
   1130                 yield obj
   1131                 # Update and possibly print the progressbar.

~/anaconda3/lib/python3.7/multiprocessing/pool.py in <genexpr>(.0)
    323                     result._set_length
    324                 ))
--> 325             return (item for chunk in result for item in chunk)
    326 
    327     def imap_unordered(self, func, iterable, chunksize=1):

~/anaconda3/lib/python3.7/multiprocessing/pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

~/anaconda3/lib/python3.7/multiprocessing/pool.py in worker()
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

~/anaconda3/lib/python3.7/multiprocessing/pool.py in mapstar()
     42 
     43 def mapstar(args):
---> 44     return list(map(*args))
     45 
     46 def starmapstar(args):

~/anaconda3/lib/python3.7/site-packages/navis/core/neuronlist.py in _worker_wrapper()
    719 def _worker_wrapper(x: Sequence):
    720     f, args, kwargs = x
--> 721     return f(*args, **kwargs)
    722 
    723 

~/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py in prune_by_volume()
   1420             x = self
   1421         else:
-> 1422             x = self.copy()
   1423 
   1424         intersection.in_volume(x, v, inplace=True,

~/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py in copy()
   1011         """
   1012         # Generate new neuron
-> 1013         x = Neuron(self.nodes)
   1014         # Override with this neuron's data
   1015         x.__dict__.update({k: copy.copy(v) for k, v in self.__dict__.items()})

~/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py in __getattr__()
    701 
    702         # Last ditch effort - maybe the base class knows the key?
--> 703         return super().__getattr__(key)
    704 
    705     def __truediv__(self, other):

~/anaconda3/lib/python3.7/site-packages/navis/core/neurons.py in __getattr__()
    123             return None
    124 
--> 125         raise AttributeError(f'Attribute "{key}" not found')
    126 
    127     def __str__(self):

AttributeError: Attribute "nodes" not found

```

**Comment by schlegelp** [comment]
Sorry, I made a stupid mistake. No clue how this worked in my tests in the first place - maybe accidentally deleted a line before making the commit. Please try again.

**Comment by SridharJagannathan** [comment]
Thanks again @schlegelp It works now.. :)
